AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation stack para criar instância EC2 Spot para rodar a API Orfanato NIB'

Parameters:
  Environment:
    Type: String
    Description: Ambiente de deploy (staging, production, dev)
    Default: staging
    AllowedValues:
      - staging
      - production
      - dev
  
  InstanceType:
    Type: String
    Description: Tipo de instância EC2 (t3.micro é a mais barata - recomendado para pequeno porte)
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3.small
  
  SpotPrice:
    Type: String
    Description: Preço máximo para Spot Instance (deixe vazio para usar preço atual do mercado - mais barato)
    Default: ''
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: ID da VPC onde a instância será criada
  
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: ID da subnet pública onde a instância será criada
  
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Nome do par de chaves EC2 para acesso SSH
  
  AllowedCIDR:
    Type: String
    Description: CIDR permitido para acessar a API (0.0.0.0/0 = qualquer IP)
    Default: 0.0.0.0/0
  
  GitHubRepo:
    Type: String
    Description: 'URL do repositório GitHub (ex: https://github.com/user/repo.git)'
    Default: ''
  
  GitHubBranch:
    Type: String
    Description: Branch do repositório para fazer deploy
    Default: main
  
  # Variáveis de ambiente da aplicação
  DBHost:
    Type: String
    Description: Host do banco de dados RDS
    Default: ''
  
  DBPort:
    Type: String
    Description: Porta do banco de dados
    Default: '3306'
  
  DBUsername:
    Type: String
    Description: Usuário do banco de dados
    Default: ''
    NoEcho: true
  
  DBPassword:
    Type: String
    Description: Senha do banco de dados
    Default: ''
    NoEcho: true
  
  DBName:
    Type: String
    Description: Nome do banco de dados
    Default: ''
  
  AWSRegion:
    Type: String
    Description: Região AWS
    Default: us-east-1
  
  AMIId:
    Type: String
    Description: 'ID da AMI (Amazon Linux 2023). Para us-east-1: ami-08d7aabbb50c2c24e'
    Default: ami-08d7aabbb50c2c24e
  
  AWSAccessKeyId:
    Type: String
    Description: AWS Access Key ID
    Default: ''
    NoEcho: true
  
  AWSSecretAccessKey:
    Type: String
    Description: AWS Secret Access Key
    Default: ''
    NoEcho: true
  
  S3BucketName:
    Type: String
    Description: Nome do bucket S3
    Default: ''
  
  SESDefaultFrom:
    Type: String
    Description: Email remetente padrão do SES
    Default: ''
  
  SESDefaultTo:
    Type: String
    Description: Email destinatário padrão do SES (separados por vírgula)
    Default: ''
  
  DomainName:
    Type: String
    Description: 'Domínio base (ex: orfanatonib.com)'
    Default: orfanatonib.com
  
  HostedZoneId:
    Type: String
    Description: ID da Hosted Zone do Route53 (deixe vazio se não tiver)
    Default: ''

Resources:
  # IAM Role para a instância EC2
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Environment}-orfanato-nib-ec2-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      # Removido AmazonS3ReadOnlyAccess - usando apenas políticas customizadas para reduzir custos
      Policies:
        - PolicyName: SESAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ses:SendEmail
                  - ses:SendRawEmail
                Resource: '*'
        - PolicyName: S3BucketAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${S3BucketName}'
                  - !Sub 'arn:aws:s3:::${S3BucketName}/*'
        - PolicyName: ECRAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: '*'
        - PolicyName: SSMAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:UpdateInstanceInformation
                  - ssmmessages:CreateControlChannel
                  - ssmmessages:CreateDataChannel
                  - ssmmessages:OpenControlChannel
                  - ssmmessages:OpenDataChannel
                Resource: '*'
      Tags:
        - Key: Application
          Value: orfanato-nib
        - Key: Environment
          Value: !Ref Environment
  
  # IAM Instance Profile
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2InstanceRole
  
  # Security Group para a instancia EC2
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${Environment}-orfanato-nib-ec2-sg'
      GroupDescription: Security Group for EC2 instance of Orfanato NIB API
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref AllowedCIDR
          Description: HTTP
        # HTTPS removido para reduzir custos - pode adicionar depois se necessário
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowedCIDR
          Description: SSH
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: !Ref AllowedCIDR
          Description: API Port
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic
      Tags:
        - Key: Application
          Value: orfanato-nib
        - Key: Environment
          Value: !Ref Environment
  
  # Launch Template para Spot Instance (configurado para custos mínimos)
  SpotLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub '${Environment}-orfanato-nib-spot-template'
      LaunchTemplateData:
        ImageId: !Ref AMIId
        InstanceType: !Ref InstanceType
        IamInstanceProfile:
          Name: !Ref EC2InstanceProfile
        KeyName: !Ref KeyPairName
        SecurityGroupIds:
          - !Ref EC2SecurityGroup
        InstanceMarketOptions:
          MarketType: spot
          SpotOptions:
            SpotInstanceType: one-time
            MaxPrice: !If [HasSpotPrice, !Ref SpotPrice, "0.005"]
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: 8
              VolumeType: gp3
              DeleteOnTermination: true
              Encrypted: false
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            set -e
            
            # Atualizar apenas pacotes de segurança (mais rápido e barato)
            yum update-minimal --security -y
            
            # Instalar Docker
            yum install -y docker
            systemctl enable docker
            systemctl start docker
            usermod -aG docker ec2-user
            
            # Instalar AWS CLI v2 (mais recente)
            if ! command -v aws &> /dev/null; then
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              yum install -y unzip
              unzip awscliv2.zip
              ./aws/install
            fi
            
            # Instalar SSM Agent (necessário para AWS Systems Manager)
            yum install -y amazon-ssm-agent
            systemctl enable amazon-ssm-agent
            systemctl start amazon-ssm-agent
            
            # Criar diretório para arquivos de ambiente
            mkdir -p /opt/orfanato-nib-api/env
            
            # Criar arquivo .env
            cat > /opt/orfanato-nib-api/env/${Environment}.env <<EOF
            ENVIRONMENT=${Environment}
            
            DB_HOST=${DBHost}
            DB_PORT=${DBPort}
            DB_USERNAME=${DBUsername}
            DB_PASSWORD=${DBPassword}
            DB_NAME=${DBName}
            
            AWS_REGION=${AWSRegion}
            AWS_ACCESS_KEY_ID=${AWSAccessKeyId}
            AWS_SECRET_ACCESS_KEY=${AWSSecretAccessKey}
            AWS_S3_BUCKET_NAME=${S3BucketName}
            
            SES_DEFAULT_FROM=${SESDefaultFrom}
            SES_DEFAULT_TO=${SESDefaultTo}
            
            JWT_SECRET=${JwtSecret}
            JWT_EXPIRES_IN=7d
            JWT_REFRESH_SECRET=${JwtRefreshSecret}
            JWT_REFRESH_EXPIRES_IN=14d
            
            TWILIO_ACCOUNT_SID=${TwilioAccountSid}
            TWILIO_AUTH_TOKEN=${TwilioAuthToken}
            TWILIO_WHATSAPP_FROM=${TwilioWhatsAppFrom}
            TWILIO_WHATSAPP_TO=${TwilioWhatsAppTo}
            
            FEED_CLUBINHO_PAGE_ID=${FeedClubinhoPageId}
            
            GOOGLE_CLIENT_ID=${GoogleClientId}
            EOF
            
            # Nota: A imagem Docker será baixada e executada via script de deploy
            # Execute: bash docker-deploy-ec2.sh ${Environment} latest
            
            # Nginx removido para reduzir custos - aplicação roda diretamente na porta 3000
            # Se precisar de reverse proxy, pode adicionar depois
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub '${Environment}-orfanato-nib-api'
              - Key: Application
                Value: orfanato-nib
              - Key: Environment
                Value: !Ref Environment
              - Key: InstanceType
                Value: Spot
  
  # EC2 Spot Instance (configurada para custos mínimos via Launch Template)
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref SpotLaunchTemplate
        Version: !GetAtt SpotLaunchTemplate.LatestVersionNumber
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-orfanato-nib-api'
        - Key: Application
          Value: orfanato-nib
        - Key: Environment
          Value: !Ref Environment
        - Key: InstanceType
          Value: Spot
        - Key: CostOptimization
          Value: SpotInstance

  # Registro DNS no Route53 (automático - criado após instância estar pronta)
  # DNS para Staging
  StagingAPIDNSRecord:
    Type: AWS::Route53::RecordSet
    Condition: HasHostedZoneAndStaging
    DependsOn: EC2Instance
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub 'staging-api.${DomainName}'
      Type: A
      TTL: 300
      ResourceRecords:
        - !GetAtt EC2Instance.PublicIp
  
  # DNS para Production
  ProductionAPIDNSRecord:
    Type: AWS::Route53::RecordSet
    Condition: HasHostedZoneAndProduction
    DependsOn: EC2Instance
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub 'api.${DomainName}'
      Type: A
      TTL: 300
      ResourceRecords:
        - !GetAtt EC2Instance.PublicIp

Conditions:
  HasGitHubRepo: !Not [!Equals [!Ref GitHubRepo, '']]
  HasSpotPrice: !Not [!Equals [!Ref SpotPrice, '']]
  HasHostedZone: !Not [!Equals [!Ref HostedZoneId, '']]
  IsStaging: !Equals [!Ref Environment, 'staging']
  IsProduction: !Equals [!Ref Environment, 'production']
  HasHostedZoneAndStaging: !And
    - !Condition HasHostedZone
    - !Condition IsStaging
  HasHostedZoneAndProduction: !And
    - !Condition HasHostedZone
    - !Condition IsProduction

Outputs:
  InstanceId:
    Description: ID da instância EC2 criada
    Value: !Ref EC2Instance
    Export:
      Name: !Sub '${AWS::StackName}-InstanceId'
  
  PublicIP:
    Description: IP público da instância
    Value: !GetAtt EC2Instance.PublicIp
    Export:
      Name: !Sub '${AWS::StackName}-PublicIP'
  
  LaunchTemplateId:
    Description: ID do Launch Template
    Value: !Ref SpotLaunchTemplate
    Export:
      Name: !Sub '${AWS::StackName}-LaunchTemplateId'
  
  SecurityGroupId:
    Description: ID do Security Group
    Value: !Ref EC2SecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-SecurityGroupId'
  
  InstanceProfileArn:
    Description: ARN do IAM Instance Profile
    Value: !GetAtt EC2InstanceProfile.Arn
    Export:
      Name: !Sub '${AWS::StackName}-InstanceProfileArn'
  
  Subdomain:
    Description: Subdomínio configurado para a API
    Value: !If
      - IsStaging
      - !Sub 'staging-api.${DomainName}'
      - !If
        - IsProduction
        - !Sub 'api.${DomainName}'
        - !Sub '${Environment}-api.${DomainName}'
  
  APIUrl:
    Description: URL da API (atualize DNS manualmente após obter o IP)
    Value: !If
      - IsStaging
      - !Sub 'http://staging-api.${DomainName}'
      - !If
        - IsProduction
        - !Sub 'http://api.${DomainName}'
        - !Sub 'http://${Environment}-api.${DomainName}'
  
  DNSUpdateNote:
    Description: Instruções para atualizar DNS
    Value: !Sub 'Execute: bash update-dns.sh ${Environment} <hosted-zone-id> após obter o IP público da instância'
  
  Note:
    Description: Nota sobre acesso à instância
    Value: !Sub 'IP público disponível no output PublicIP. Para converter para Spot Instance, use o AWS Console ou CLI'
