AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation stack para criar um bucket S3 público para armazenamento de arquivos (otimizado para baixo custo)'

Parameters:
  BucketName:
    Type: String
    Description: Nome do bucket S3 (deve ser único globalmente)
    Default: orfanato-nib-storage
  
  Environment:
    Type: String
    Description: Ambiente de deploy (staging, production, dev)
    Default: staging
    AllowedValues:
      - staging
      - production
      - dev

Resources:
  # Bucket S3 - Otimizado para baixo custo
  PublicStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      # Versionamento desabilitado para economizar (cada versão custa)
      VersioningConfiguration:
        Status: Suspended
      # Lifecycle policy para reduzir custos
      # Mover arquivos não acessados há 30 dias para Standard-IA (50% mais barato, acesso imediato)
      LifecycleConfiguration:
        Rules:
          - Id: MoveToStandardIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
      # CORS configurado para permitir acesso público
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedOrigins:
              - '*'
            ExposedHeaders:
              - ETag
            MaxAge: 3000
      # Tags para organização
      Tags:
        - Key: Application
          Value: orfanato-nib
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation
        - Key: CostOptimization
          Value: enabled

  # Política de bucket para permitir leitura pública
  PublicReadPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PublicStorageBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${PublicStorageBucket.Arn}/*'
          - Sid: PublicListBucket
            Effect: Allow
            Principal: '*'
            Action: 's3:ListBucket'
            Resource: !GetAtt PublicStorageBucket.Arn
            Condition:
              StringLike:
                's3:prefix':
                  - '*'

Outputs:
  BucketName:
    Description: Nome do bucket S3 criado
    Value: !Ref PublicStorageBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'
  
  BucketArn:
    Description: ARN do bucket S3
    Value: !GetAtt PublicStorageBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BucketArn'
  
  BucketDomainName:
    Description: Nome de domínio do bucket (para URLs públicas)
    Value: !GetAtt PublicStorageBucket.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-BucketDomainName'
  
  BucketRegionalDomainName:
    Description: Nome de domínio regional do bucket
    Value: !GetAtt PublicStorageBucket.RegionalDomainName
    Export:
      Name: !Sub '${AWS::StackName}-BucketRegionalDomainName'
  
  PublicURL:
    Description: URL pública base do bucket (para acessar arquivos)
    Value: !Sub 'https://${PublicStorageBucket}.s3.amazonaws.com'
    Export:
      Name: !Sub '${AWS::StackName}-PublicURL'
